#!/usr/bin/env python

#
# fire up a web server in the PWD
#
# give basic args for ... $0 port, $0 127.0.0.1:666, etc.
#

import os
import sys
import BaseHTTPServer
from   SimpleHTTPServer import SimpleHTTPRequestHandler

HandlerClass = SimpleHTTPRequestHandler
ServerClass  = BaseHTTPServer.HTTPServer
Protocol     = "HTTP/1.0"

server='127.0.0.1'
server='0.0.0.0'

#if sys.argv[1:]:
#    port = int(sys.argv[1])
#else:
port=8081
html_file = sys.argv[1]

# if len(sys.argv) > 1:
#    arg = sys.argv[1]
#    if ':' in arg:
#       server, port = arg.split(':')
#       port = int(port)
#    else:
#       try:
#          port = int(sys.argv[1])
#       except:
#          server = sys.argv[1]

url = "http://%s:%s/%s" % (server, port, html_file)

server_address = (server, port)
HandlerClass.protocol_version = Protocol

try:
   httpd = ServerClass(server_address, HandlerClass)
   sa = httpd.socket.getsockname()
   print "Serving webs @\n\n\t%s\n\n" % url
   httpd.serve_forever()
except Exception, err:
   print "couldn't start web server: %s" % err

